// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1TmC0n8n5ZHL-btq2yxTpYC1gnazYt4',
    appId: '1:668647163068:web:9cf0304d1d8ca7f7287cb9',
    messagingSenderId: '668647163068',
    projectId: 'notes-48f47',
    authDomain: 'notes-48f47.firebaseapp.com',
    storageBucket: 'notes-48f47.appspot.com',
    measurementId: 'G-DDL3PQ2YPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEX9qWrTJVIpJybSEj9_0BqLNEkZYteq4',
    appId: '1:668647163068:android:6b982e48a75110e7287cb9',
    messagingSenderId: '668647163068',
    projectId: 'notes-48f47',
    storageBucket: 'notes-48f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4cz6LZAJIRFdspHEuRGkd1zhU8HflZk',
    appId: '1:668647163068:ios:6c03847cb661ebad287cb9',
    messagingSenderId: '668647163068',
    projectId: 'notes-48f47',
    storageBucket: 'notes-48f47.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4cz6LZAJIRFdspHEuRGkd1zhU8HflZk',
    appId: '1:668647163068:ios:efb010a341eeb4f1287cb9',
    messagingSenderId: '668647163068',
    projectId: 'notes-48f47',
    storageBucket: 'notes-48f47.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
